---@class (exact) FolderIconConfig
---@field icon? string
---@field hl string | { clone: string }
---@field folder_names? string[]

---@type table<string, FolderIconConfig>
return {
  -- NOTE: use folder-shaped icons

  -- TODO: extend based on:
  -- https://github.com/material-extensions/vscode-material-icon-theme/blob/5a653d98f2a1bb7ee7aae28a78c60ef21c911fd0/src/core/icons/folderIcons.ts
  -- Folder-prefixed highlight groups colors should come from:
  -- https://github.com/material-extensions/vscode-material-icon-theme/blob/5a653d98f2a1bb7ee7aae28a78c60ef21c911fd0/material-colors.yml

  -- TODO:try to get similar icons and colors from:
  -- https://raw.githubusercontent.com/material-extensions/vscode-material-icon-theme/main/images/fileIcons.png
  -- https://raw.githubusercontent.com/material-extensions/vscode-material-icon-theme/main/images/folderIcons.png
  ['.changeset'] = { hl = 'FolderChangesets' },
  ['.idea'] = { hl = 'FolderIntellij' },
  ['.local'] = { icon = '󰉌', hl = 'FolderCyan' },
  ['.vim'] = { hl = 'DevIconVim' },
  ['.vscode'] = { hl = 'FolderVscode' },
  api = {
    icon = '󰴉',
    hl = 'FolderApi',
    folder_names = { 'api', 'apis', 'restapi' },
  },
  AppData = { icon = '󰉌', hl = 'FolderDeepOrange' },
  app = {
    icon = '󱧺',
    hl = 'FolderApp',
    folder_names = { 'Applications', 'app', 'application', 'applications', 'apps' },
  },
  astro = {
    hl = 'DevIconAstro',
    folder_names = { '.astro', 'astro' },
  },
  audio = {
    icon = '󱍙',
    hl = 'FolderAudio',
    folder_names = {
      'Music',
      'aud',
      'audio',
      'audios',
      'auds',
      'music',
      'recordings',
      'sound',
      'sounds',
      'voice',
      'voices',
    },
  },
  bin = {
    icon = '󱧺',
    hl = 'FolderDist',
    folder_names = { '.bin', 'bin' },
  },
  boot = { icon = '󰴋', hl = 'FolderBoot' },
  c = { hl = 'DevIconC' },
  cinnamon = {
    hl = 'DevIconCinnamon',
    folder_names = { 'cinnamon', 'cinnamon-session' },
  },
  class = {
    hl = 'FolderClass',
    folder_names = {
      'class',
      'classes',
      'model',
      'models',
      'schema',
      'schemas',
    },
  },
  client = {
    hl = 'FolderClient',
    folder_names = {
      'client',
      'clients',
      'frontend',
      'frontends',
      'pwa',
      'spa',
    },
  },
  config = {
    icon = '󱁿',
    hl = 'FolderConfig',
    folder_names = {
      '.config',
      '.settings',
      'after',
      'cfg',
      'cfgs',
      'conf',
      'config',
      'configs',
      'configuration',
      'configurations',
      'confs',
      'META-INF',
      'option',
      'options',
      'pref',
      'preference',
      'preferences',
      'prefs',
      'setting',
      'settings',
    },
  },
  connection = {
    hl = 'FolderConnection',
    folder_names = {
      'connection',
      'connections',
      'integration',
      'integrations',
      'remote',
      'remotes',
    },
  },
  content = {
    icon = '󰲂',
    hl = 'FolderContent',
    folder_names = { 'content', 'contents' },
  },
  controller = {
    icon = '󱁿',
    hl = 'FolderController',
    folder_names = {
      'controller',
      'controllers',
      'controls',
      'handler',
      'handlers',
      'provider',
      'providers',
      'service',
      'services',
    },
  },
  compiler = { icon = '󱁽', hl = 'FolderGreen' },
  components = {
    icon = '󱋣',
    hl = 'FolderComponents',
    folder_names = { 'components', 'fragmments', 'widget', 'widgets' },
  },
  css = {
    icon = '󰣞',
    hl = 'DevIconCss',
    folder_names = { 'css', 'style', 'styles', 'stylesheet', 'stylesheets' },
  },
  desktop = {
    icon = '󰚝',
    hl = 'FolderDesktop',
    folder_names = { 'Desktop', 'desktop', 'display' },
  },
  development = {
    icon = '󱧼',
    hl = 'FolderDevelopment',
    folder_names = { 'dev', 'development' },
  },
  dist = {
    icon = '󱧼',
    hl = 'FolderDist',
    folder_names = {
      'build',
      'builds',
      'dist',
      'distribution',
      'out',
      'output',
      'Release',
      'release',
    },
  },
  Documents = { icon = '󱧶', hl = 'FolderDocuments' },
  docs = {
    icon = '󱂷',
    hl = 'FolderDocs',
    folder_names = {
      'article',
      'articles',
      'doc',
      'docs',
      'document',
      'documentation',
      'documents',
      'news',
      'post',
      'posts',
      'wiki',
    },
  },
  download = {
    icon = '󰉍',
    hl = 'FolderDownload',
    folder_names = {
      'Downloads',
      'download',
      'downloader',
      'downloaders',
      'downloads',
    },
  },
  emmbedded_template = { icon = '󱋣', hl = 'DevIconEjs' },
  error = {
    hl = 'FolderError',
    folder_names = { 'crash', 'crashes', 'err', 'error', 'errors', 'errs' },
  },
  etc = { icon = '󱁿', hl = 'FolderOther' },
  examples = {
    hl = 'FolderExamples',
    folder_names = {
      'demo',
      'demos',
      'example',
      'examples',
      'sample',
      'sample-data',
      'samples',
    },
  },
  Favorites = { icon = '󱃪', hl = 'FolderFavorites' },
  font = {
    hl = 'FolderFont',
    folder_names = { 'font', 'fonts' },
  },
  ftdetect = { icon = '󱁽', hl = 'FolderGreen' },
  functions = {
    icon = '󱁽',
    hl = 'FolderFunctions',
    folder_names = {
      'autoload',
      'func',
      'funcs',
      'function',
      'functions',
      'lambda',
      'lambdas',
      'logic',
      'math',
      'maths',
      'calc',
      'calcs',
      'calculation',
      'calculations',
    },
  },
  generator = {
    icon = '󱋣',
    hl = 'FolderGenerator',
    folder_names = {
      'auto',
      'cfn-gen',
      'gen',
      'generated',
      'generated-sources',
      'generator',
      'generators',
      'gens',
    },
  },
  github = {
    icon = '',
    hl = 'FolderGithub',
    folder_names = { '.github', 'gh' },
  },
  git = {
    icon = '',
    hl = 'DevIconGitLogo',
    folder_names = { '.git', 'git', 'githooks', 'patches', 'submodules' },
  },
  go = { hl = 'DevIconGo' },
  gradle = {
    hl = 'DevIconGradle',
    folder_names = { '.gradle', 'buildSrc', 'gradle' },
  },
  groovy = { hl = 'DevIconGroovy' },
  gtk = {
    hl = 'DevIconGtk',
    folder_names = { 'gtk-2.0', 'gtk-3.0', 'gtk-4.0' },
  },
  home = {
    icon = '󱂵',
    hl = 'FolderHome',
    folder_names = { 'home', 'landing', 'main', 'start' },
  },
  html = { icon = '󱋣', hl = 'DevIconHtml' },
  i18n = {
    icon = '󱁽',
    hl = 'FolderI18n',
    folder_names = {
      'i18n',
      'internationalization',
      'l10n',
      'lang',
      'langs',
      'language',
      'languages',
      'locale',
      'locales',
      'localization',
      'translate',
      'translation',
      'translations',
      'tx',
    },
  },
  images = {
    icon = '󰉏',
    hl = 'FolderImages',
    folder_names = {
      '.icons',
      'fig',
      'figs',
      'figure',
      'figures',
      'ico',
      'icon',
      'icons',
      'icos',
      'image',
      'images',
      'img',
      'imgs',
      'photo',
      'photograph',
      'photographs',
      'photos',
      'pic',
      'pics',
      'picture',
      'Pictures',
      'pictures',
      'screengrab',
      'screengrabs',
      'screenshot',
      'screenshots',
    },
  },
  indent = { icon = '󱁽', hl = 'MiniIconsGreen' },
  java = {
    hl = 'DevIconJava',
    folder_names = { '.java', 'java', 'jre' },
  },
  javascript = {
    -- NOTE: for filetype-releated directories, use DevIcon's highlight groups
    -- these are defined by the `nvim-web-devicons` plugin
    hl = 'DevIconJs',
    folder_names = { 'ecma', 'javascript', 'javascripts', 'js' },
  },
  layout = {
    icon = '󱋣',
    hl = 'FolderLayout',
    folder_names = { 'layout', 'layouts' },
  },
  lib = {
    icon = '󰲂',
    hl = 'FolderLib',
    folder_names = {
      'Library',
      'lib',
      'lib64',
      'libraries',
      'library',
      'libs',
      'third-party',
      'vendor',
      'vendors',
    },
  },
  log = {
    icon = '󱂷',
    hl = 'FolderLog',
    folder_names = { 'log', 'logging', 'logs' },
  },
  -- TODO: use `FolderLsp` highlight group
  -- take color from header background of:
  -- https://microsoft.github.io/language-server-protocol/
  lsp = { icon = '󱁽', hl = 'MiniIconsGreen' },
  lua = { hl = 'FolderLua' },
  mappings = {
    icon = '󱁽',
    hl = 'FolderMappings',
    folder_names = { 'keymap', 'mapping', 'mappings' },
  },
  markdown = {
    hl = 'DevIconMarkdown',
    folder_names = { 'markdown', 'md' },
  },
  media = { icon = '󱧺', hl = 'FolderVideo' },
  mnt = { icon = '󰉓', hl = 'MiniIconsYellow' },
  mock = {
    icon = '󰣞',
    hl = 'FolderMock',
    folder_names = {
      'concept',
      'concepts',
      'draft',
      'drafts',
      'fixture',
      'fixtures',
      'mock',
      'mocks',
      'sketch',
      'sketches',
    },
  },
  netlify = {
    hl = 'FolderNetlify',
    folder_names = { '.netlify', 'netlify' },
  },
  node = {
    icon = '',
    hl = 'FolderNode',
    folder_names = { '.npm', 'node', 'node_modules', 'nodejs', 'npm' },
  },
  neovim = {
    hl = 'DevIconVim',
    folder_names = { 'neovim', 'nvim' },
  },
  opt = { icon = '󰉗', hl = 'MiniIconsYellow' },
  other = {
    hl = 'FolderOther',
    folder_names = {
      'other',
      'others',
      'misc',
      'miscellaneous',
      'extra',
      'extras',
    },
  },
  packages = {
    icon = '󱁽',
    hl = 'FolderPackages',
    folder_names = {
      'dependencies',
      'devpackages',
      'pack',
      'package',
      'packages',
      'pkg',
      'pkgs',
      'serverpackages',
    },
  },
  parser = { icon = '󱁽', hl = 'MiniIconsGreen' },
  plugin = {
    icon = '󱁽',
    hl = 'FolderPlugin',
    folder_names = {
      'addin',
      'addins',
      'addon',
      'addons',
      'extension',
      'extensions',
      'ftplugin',
      'mod',
      'modding',
      'mods',
      'module',
      'modules',
      'plugin',
      'plugins',
      'rplugin',
    },
  },
  pnpm = { hl = 'FolderPnpm' },
  proc = { icon = '󰢬', hl = 'MiniIconsYellow' },
  ProgramData = { icon = '󰉌', hl = 'FolderDeepOrange' },
  public = {
    icon = '󱧰',
    hl = 'FolderPublic',
    folder_names = {
      'Public',
      'browser',
      'browsers',
      'public',
      'site',
      'web',
      'website',
      'websites',
      'www',
      'wwwroot',
    },
  },
  python = {
    hl = 'DevIconPy',
    folder_names = { 'pycache', 'pytest_cache', 'python' },
  },
  queries = { icon = '󱁽', hl = 'MiniIconsGreen' },
  react = { hl = 'DevIconJsx' },
  resource = {
    icon = '󱧶',
    hl = 'FolderResource',
    folder_names = {
      'asset',
      'assets',
      'report',
      'reports',
      'res',
      'resource',
      'resources',
      'static',
    },
  },
  root = { icon = '󰷌', hl = 'MiniIconsYellow' },
  run = { icon = '󱧺', hl = 'FolderRun' },
  rust = { hl = 'DevIconRs' },
  sass = {
    hl = 'DevIconScss',
    folder_names = { 'sass', 'sass-utils', 'scss' },
  },
  sbin = { icon = '󱧺', hl = 'MiniIconsYellow' },
  scripts = {
    icon = '󰴉',
    hl = 'FolderScripts',
    folder_names = { 'script', 'scripting', 'scripts' },
  },
  server = {
    hl = 'FolderServer',
    folder_names = { 'backend', 'backends', 'server', 'servers', 'ssr' },
  },
  shared = {
    icon = '󰡰',
    hl = 'FolderShared',
    folder_names = { 'Network', 'common', 'shared' },
  },
  shell = { icon = '󰴉', hl = 'DevIconSh' },
  snippet = {
    icon = '󱁽',
    hl = 'FolderSnippets',
    folder_names = { 'snippet', 'snippets' },
  },
  store = {
    hl = 'FolderStore',
    folder_names = { 'store', 'stores' },
  },
  swift = { hl = 'DevIconSwift' },
  syntax = {
    icon = '󱁽',
    hl = 'FolderSyntax',
    folder_names = { 'spell', 'spellcheck', 'spellcheckers', 'syntax', 'syntaxes' },
  },
  System = { icon = '󱧼', hl = 'FolderDeepOrange' },
  src = {
    icon = '󰴉',
    hl = 'FolderSrc',
    folder_names = { 'code', 'source', 'sources', 'src', 'srcs' },
  },
  srv = { icon = '󱋣', hl = 'MiniIconsYellow' },
  temp = {
    icon = '󰪺',
    hl = 'FolderTemp',
    folder_names = { '.cache', 'cache', 'cached', 'temp', 'tmp' },
  },
  template = {
    icon = '󱋣',
    hl = 'FolderTemplate',
    folder_names = {
      '_templates',
      'ISSUE_TEMPLATE',
      'PULL_REQUEST_TEMPLATE',
      'Template',
      'template',
      'Templates',
      'templates',
    },
  },
  test = {
    icon = '󱞊',
    hl = 'FolderTest',
    folder_names = {
      'snapshots',
      'spec',
      'specs',
      'test',
      'testing',
      'tests',
    },
  },
  toml = { hl = 'DevIconToml' },
  theme = {
    icon = '󱁽',
    hl = 'FolderTheme',
    folder_names = {
      '.themes',
      'color',
      'colors',
      'design',
      'designs',
      'theme',
      'themes',
      'theming',
    },
  },
  trash = {
    icon = '󱧴',
    hl = 'FolderTrash',
    folder_names = { 'Trash', 'trash' },
  },
  tutor = { icon = '󱁽', hl = 'MiniIconsGreen' },
  ui = {
    icon = '󱋣',
    hl = 'FolderUi',
    folder_names = { 'gui', 'presentation', 'ui', 'ux' },
  },
  user = { icon = '󰉌', hl = 'FolderDeepOrange', folder_names = { 'Users', 'usr' } },
  utils = {
    icon = '󰉗',
    hl = 'FolderUtils',
    folder_names = { 'utilities', 'utils', 'utitlity' },
  },
  var = { icon = '󱋣', hl = 'MiniIconsYellow' },
  video = {
    icon = '󱞊',
    hl = 'FolderVideo',
    folder_names = {
      'Videos',
      'movie',
      'movies',
      'vid',
      'video',
      'videos',
      'vids',
    },
  },
  views = {
    icon = '󱞊',
    hl = 'FolderViews',
    folder_names = {
      'page',
      'pages',
      'public_html',
      'screen',
      'screens',
      'view',
      'views',
    },
  },
  vite = {
    hl = 'FolderVite',
    folder_names = { '.vite', 'vite', 'vite-config', 'vitejs' },
  },
  vlc = { hl = 'DevIconVlc' },
  Volumes = { icon = '󰉓', hl = 'FolderDeepOrange' },
  windows = {
    hl = 'DevIconWindows',
    folder_names = { 'win', 'win32', 'windows' },
  },
  workflows = { hl = 'FolderGithub' },
  yaml = { hl = 'DevIconYaml' },
}
