local COLORS = require('colors')

---@type table<string, FileIconConfig>
return {
  -- TODO: extend based on:
  -- https://github.com/material-extensions/vscode-material-icon-theme/blob/main/src/core/icons/fileIcons.ts

  -- NOTE: it's not necessary to use uppercase for file names

  astro_config = {
    icon = '',
    color = '#7c4dff',
    name = 'AstroConfig',
    file_names = {
      'astro.config.cjs',
      'astro.config.cts',
      'astro.config.js',
      'astro.config.mjs',
      'astro.config.mts',
      'astro.config.ts',
    },
  },
  env = {
    icon = '',
    color = '#faf743',
    name = 'Env',
    file_names = {
      '.dev.vars',
      '.env.alpha',
      '.env.defaults',
      '.env.dev',
      '.env.dev.local',
      '.env.development',
      '.env.development.local',
      '.env.dist',
      '.env.e2e',
      '.env.example',
      '.env.local',
      '.env.preview',
      '.env.prod',
      '.env.prod.local',
      '.env.production',
      '.env.production.local',
      '.env.qa',
      '.env.qa.local',
      '.env.sample',
      '.env.schema',
      '.env.stage',
      '.env.staging',
      '.env.staging.local',
      '.env.stg',
      '.env.stg.local',
      '.env.template',
      '.env.test',
      '.env.test.local',
      '.env.testing',
      '.env.uat',
      '.vars',
    },
  },
  eslintrc = {
    icon = '',
    color = '#4b32c3',
    name = 'Eslintrc',
    file_names = {
      '.eslintrc.cjs',
      '.eslintrc.cts',
      '.eslintrc.js',
      '.eslintrc.mts',
    },
  },
  ['fabric.mod.json'] = {
    icon = '󰯁',
    color = COLORS['amber-A700'],
    name = 'FabricMod',
  },
  git = {
    icon = '',
    color = '#f54d27',
    name = 'Git',
    file_names = {
      '.git-blame-ignore',
      '.git-for-windows-updater',
      '.gitattributes-global',
      '.gitattributes_global',
      '.gitignore-global',
      '.gitignore_global',
      '.gitinclude',
      '.gitkeep',
      '.gitmessage',
      '.gitpreserve',
      '.keep',
      'git-history',
    },
  },
  ['jsconfig.json'] = {
    icon = '',
    name = 'Jsconfig',
    color = '#cbcb41',
  },
  ['lazy-lock.json'] = {
    icon = '󰒲',
    name = 'LazyLock',
    -- from: https://github.com/folke/lazy.nvim/blob/docs/static/img/icon.svg
    color = '#2e7de9',
  },
  license = {
    icon = '',
    color = '#cbcb41',
    name = 'License',
    file_names = {
      'copying.md',
      'copying.rst',
      'copying.txt',
      'copyright',
      'copyright.md',
      'copyright.rst',
      'copyright.txt',
      'licence',
      'licence-agpl',
      'licence-apache',
      'licence-bsd',
      'licence-gpl',
      'licence-lgpl',
      'licence-mit',
      'licence.md',
      'licence.rst',
      'licence.txt',
      'license-agpl',
      'license-apache',
      'license-bsd',
      'license-gpl',
      'license-lgpl',
      'license-mit',
      'license.rst',
      'license.txt',
      'unlicense.txt',
    },
  },
  ['playwright.config.js'] = {
    icon = '',
    color = COLORS['green-500'],
    name = 'PlaywrightConfigJS',
  },
  ['playwright.config.ts'] = {
    icon = '',
    color = COLORS['green-500'],
    name = 'PlaywrightConfigTS',
  },
  pnpm = {
    icon = '',
    color = COLORS['amber-600'],
    name = 'Pnpm',
    file_names = { 'pnpm-lock.yaml', 'pnpm-workspace.yaml', '.pnpmfile.cjs' },
  },
  todo = {
    icon = '',
    color = COLORS['light-green-600'],
    name = 'Todo',
    file_names = { 'todo.md', 'todos.md' },
  },
  ['tsconfig.node.json'] = {
    icon = '',
    color = '#519aba',
    name = 'TSConfig',
  },
  vite = {
    icon = '',
    color = COLORS['amber-A700'],
    name = 'Vite',
    file_names = { 'vite.config.js', 'vite.config.ts' },
  },
}
